=== eia-fr/ESIB_PAD/CodeSource/webServices/listeSalles/schemaListSalles.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="response">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="status"/>
        <xs:element ref="usrGroup"/>
        <xs:element ref="salles"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="status" type="xs:integer"/>
  <xs:element name="usrGroup" type="xs:integer"/>
  <xs:element name="salles">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="salle"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="salle">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" ref="description"/>
        <xs:element minOccurs="0" ref="img"/>
      </xs:sequence>
      <xs:attribute name="id" use="required" type="xs:integer"/>
      <xs:attribute name="latitude" use="required" type="xs:decimal"/>
      <xs:attribute name="longitude" use="required" type="xs:decimal"/>
      <xs:attribute name="nom" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="description">
    <xs:complexType>
      <xs:attribute name="value" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="img">
    <xs:complexType>
      <xs:attribute name="adresse" use="required" type="xs:anyURI"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== eia-fr/ESIB_PAD/CodeSource/webServices/listeSalles/listeSalles.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Resultat de l'appel https://www.url.com/webSerivice.php 
    avec les parametres en POST suivant:
    usr = 'user.login'
    pwd = 'password'
    op  = 'listSalles'
    param0= 'sciences_Technologies'  // Nom du campus pour les salles.Si il n'est pas envoyé, ça veut dire tout les campus
-->
<response xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="schemaListSalles.xsd">  
    <status>0</status>
    <usrGroup>2</usrGroup>
    <salles>
        <salle id="1" nom="Auditoire a" longitude="33.864901" latitude="35.564488">
            <description value="Test d'une déscription"/>
            <img adresse="http://google.ch/img1.jpg"/>
        </salle>
        <salle id="2" nom="Labo" longitude="33.864903" latitude="35.564408">
        </salle>
        <salle id="3" nom="Labo" longitude="33.864903" latitude="35.564408">
            <img adresse="http://google.ch/img1.jpg"/>
        </salle>
    </salles>
</response>
