=== eia-fr/ESIB_PAD/CodeSource/webServices/trouverBureau/schemaTrouverBureau.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="response">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="status"/>
        <xs:element ref="usrGroup"/>
        <xs:element ref="bureaux"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="status" type="xs:integer"/>
  <xs:element name="usrGroup" type="xs:integer"/>
  <xs:element name="bureaux">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="bureau"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="bureau">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" ref="description"/>
      </xs:sequence>
      <xs:attribute name="etage" type="xs:integer"/>
      <xs:attribute name="latitude" use="required" type="xs:decimal"/>
      <xs:attribute name="longitude" use="required" type="xs:decimal"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="description">
    <xs:complexType>
      <xs:attribute name="value" use="required"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== eia-fr/ESIB_PAD/CodeSource/webServices/trouverBureau.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Resultat de l'appel https://www.url.com/webSerivice.php 
    avec les parametres en POST suivant:
    usr = 'user.login'
    pwd = 'password'
    op  = 'trouverBureau'
    param0 = 'idPersonne'  // Si la valeur est égal à 0, l'id n'est pas connu.
    param1 = 'nom ou prénom ou les deux' // Valeur pour la recherche d'une personne par une chaine de texte
-->
<response xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="schemaTrouverBureau.xsd">  
    <status>0</status>
    <usrGroup>2</usrGroup>
    <bureaux>
        <bureau longitude="33.864901" latitude="35.564488" etage="3">
            <description value="Test d'une déscription"/>
        </bureau>
        <bureau longitude="33.123455" latitude="35.564488" etage="2">
        </bureau>
        <bureau longitude="33.334444" latitude="35.564488">
        </bureau>
    </bureaux>
</response>
