=== eia-fr/ESIB_PAD/CodeSource/webServices/listePersonnes/schemaListePersonne.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="response">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="status"/>
        <xs:element ref="usrGroup"/>
        <xs:element ref="personnes"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="status" type="xs:integer"/>
  <xs:element name="usrGroup" type="xs:integer"/>
  <xs:element name="personnes">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="personne"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="personne">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="description"/>
        <xs:element minOccurs="0" ref="img"/>
      </xs:sequence>
      <xs:attribute name="email" use="required"/>
      <xs:attribute name="id" use="required" type="xs:integer"/>
      <xs:attribute name="nom" use="required"/>
      <xs:attribute name="prenom" use="required"/>
      <xs:attribute name="tel" type="xs:integer"/>
      <xs:attribute name="type" use="required" type="xs:integer"/><!-- 0 représente un prof ou un étudiant, 1 représente un étudiant -->
    </xs:complexType>
  </xs:element>
  <xs:element name="description">
    <xs:complexType>
      <xs:attribute name="value" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="img">
    <xs:complexType>
      <xs:attribute name="adresse" use="required" type="xs:anyURI"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== eia-fr/ESIB_PAD/CodeSource/webServices/listePersonnes/listePersonnes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Resultat de l'appel https://www.url.com/webSerivice.php 
    avec les parametres en POST suivant:
    usr = 'user.login'
    pwd = 'password'
    op  = 'listePersonnes'
    param0= 'sciences_Technologies'  // Nom du campus.Si il n'est pas envoyé, ça veut dire tout les campus
-->
<response xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="schemaListePersonne.xsd">  
    <status>0</status>
    <usrGroup>2</usrGroup>
    <personnes>
        <personne  id="1" nom="Nom 1" prenom="Prénom 1" tel="07420000" email="test@usj.edu.lb" type="0" >
            <description value="Professeurs de Maths de l'usj"/>
            <img adresse="http://google.ch/img1.jpg"/>
        </personne>
        <personne  id="2" nom="Professeur 2" prenom="Prénom 2" email="test2@usj.edu.lb" type="0" >
            <description value="Professeurs ou collaborateur de l'usj 2"/>
        </personne>
        <personne  id="3" nom="Etudiant " prenom="Prénom 2" email="test2@usj.edu.lb" type="1" >
            <description value="Etudiant de l'usj 2"/>
        </personne>
        <personne  id="4" nom="Etudiant2 " prenom="Prénom 2" email="test2@usj.edu.lb" type="1" >
            <description value="Etudiant 2 de l'usj 2"/>
        </personne>
    </personnes>
</response>
